import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Custom Components
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// UI
import '@mantine/core/styles.css';
import { createTheme, MantineProvider, rem } from '@mantine/core';
import { ColorSchemeScript } from '@mantine/core';
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({

  shadows: {
    md: '1px 1px 3px rgba(0, 0, 0, .25)',
    xl: '5px 5px 3px rgba(0, 0, 0, .25)',
  },

  headings: {
    fontFamily: 'Roboto, sans-serif',
    sizes: {
      h1: { fontSize: rem(36) },
    },
  },
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </Head>
      <body className={inter.className}>
        <MantineProvider theme={theme} defaultColorScheme="dark">
          <Navbar />
          {children}
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}
